// Package main demonstrates a minimal P2P chat between two agents.
//
// In a full deployment, agents connect via WebRTC data channels with
// signaling through a PeerClaw server or Nostr relays. This example
// shows the agent-level messaging API (OnMessage, Send, envelope
// construction) using direct in-process delivery to keep the example
// self-contained and runnable without any external infrastructure.
//
// Run: go run .
package main

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"sync"

	"github.com/peerclaw/peerclaw-core/envelope"
	"github.com/peerclaw/peerclaw-core/protocol"
)

// loopbackDelivery is a simple in-process message bus that delivers
// envelopes by destination ID. It substitutes for the real WebRTC +
// signaling transport so the example can run standalone.
type loopbackDelivery struct {
	mu       sync.RWMutex
	handlers map[string]func(ctx context.Context, env *envelope.Envelope)
}

func newLoopbackDelivery() *loopbackDelivery {
	return &loopbackDelivery{
		handlers: make(map[string]func(ctx context.Context, env *envelope.Envelope)),
	}
}

// register associates an agent ID with its incoming-message handler.
func (lb *loopbackDelivery) register(id string, handler func(ctx context.Context, env *envelope.Envelope)) {
	lb.mu.Lock()
	lb.handlers[id] = handler
	lb.mu.Unlock()
}

// send delivers an envelope to the handler registered for env.Destination.
func (lb *loopbackDelivery) send(ctx context.Context, env *envelope.Envelope) error {
	lb.mu.RLock()
	h, ok := lb.handlers[env.Destination]
	lb.mu.RUnlock()
	if !ok {
		return fmt.Errorf("no handler for destination %q", env.Destination)
	}
	h(ctx, env)
	return nil
}

func main() {
	logger := slog.New(slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelInfo}))

	ctx := context.Background()

	// ---------------------------------------------------------------
	// Step 1: Create a loopback message bus.
	//
	// In production, the Agent.Send method tries a WebRTC P2P data
	// channel first, then falls back to a signaling relay. Here we
	// use a trivial in-process map so two "agents" can exchange
	// envelopes without any network setup.
	// ---------------------------------------------------------------
	bus := newLoopbackDelivery()

	// ---------------------------------------------------------------
	// Step 2: Define agent identities.
	//
	// Normally these come from Ed25519 keypairs generated by the SDK.
	// We use plain strings for this demonstration.
	// ---------------------------------------------------------------
	const aliceID = "alice"
	const bobID = "bob"

	// wg tracks when both agents have finished their conversation.
	var wg sync.WaitGroup

	// ---------------------------------------------------------------
	// Step 3: Set up Alice's message handler.
	//
	// OnMessage registers a callback that fires for every incoming
	// envelope. Alice prints what she receives and sends a reply.
	// ---------------------------------------------------------------
	wg.Add(1)
	bus.register(aliceID, func(ctx context.Context, env *envelope.Envelope) {
		logger.Info("[Alice] received message",
			"from", env.Source,
			"type", env.MessageType,
			"payload", string(env.Payload),
		)

		// Alice replies to Bob.
		reply := envelope.New(aliceID, bobID, protocol.ProtocolA2A, []byte("Hi Bob, nice to meet you!"))
		reply.MessageType = envelope.MessageTypeResponse

		logger.Info("[Alice] sending reply", "to", reply.Destination)
		if err := bus.send(ctx, reply); err != nil {
			logger.Error("[Alice] send failed", "error", err)
		}
		wg.Done()
	})

	// ---------------------------------------------------------------
	// Step 4: Set up Bob's message handler.
	//
	// Bob receives Alice's reply and the conversation ends.
	// ---------------------------------------------------------------
	wg.Add(1)
	bus.register(bobID, func(ctx context.Context, env *envelope.Envelope) {
		logger.Info("[Bob] received message",
			"from", env.Source,
			"type", env.MessageType,
			"payload", string(env.Payload),
		)
		wg.Done()
	})

	// ---------------------------------------------------------------
	// Step 5: Bob initiates the conversation.
	//
	// envelope.New creates a signed, timestamped envelope with a
	// unique ID and trace ID. In production, Agent.Send would sign
	// the payload, optionally encrypt it with a session key, and
	// deliver it over WebRTC or relay.
	// ---------------------------------------------------------------
	msg := envelope.New(bobID, aliceID, protocol.ProtocolA2A, []byte("Hello Alice!"))
	msg.MessageType = envelope.MessageTypeRequest

	logger.Info("[Bob] sending initial message", "to", msg.Destination)
	if err := bus.send(ctx, msg); err != nil {
		logger.Error("[Bob] send failed", "error", err)
		os.Exit(1)
	}

	// ---------------------------------------------------------------
	// Step 6: Wait for the conversation to complete.
	// ---------------------------------------------------------------
	wg.Wait()

	fmt.Println()
	fmt.Println("=== Chat Complete ===")
	fmt.Println("  Bob  -> Alice: Hello Alice!")
	fmt.Println("  Alice -> Bob:  Hi Bob, nice to meet you!")
	fmt.Println()

	logger.Info("p2p-chat example complete")
}
